# Generated by Django 5.0.7 on 2024-09-08 14:19

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_paydoc_id', models.CharField(blank=True, max_length=255, verbose_name='Номер платежа в системе CLICK')),
                ('amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=9, verbose_name='Сумма оплаты (в сумах)')),
                ('action', models.CharField(blank=True, max_length=255, null=True, verbose_name='Выполняемое действие')),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('processing', 'processing'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('error', 'error')], default='waiting', max_length=25, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/package_images')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('duration', models.CharField(max_length=100)),
                ('depart_time', models.DateField()),
                ('return_time', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.packages')),
            ],
        ),
    ]
